---
abstract: 'A rss/atom reader which delivers entries to your mailboxes'
author:
  - 'Olivier Schwander <olivier.schwander@ens-lyon.org>'
build_requires:
  Test::Dependencies: 0
  Test::More: 0.42
distribution_type: module
generated_by: 'Module::Install version 0.79'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: cnutt-feed
no_index:
  directory:
    - inc
    - t
    - test
requires:
  Config::Tiny: 0
  Email::Address: 0
  Email::Date: 0
  Email::Folder: 0
  Email::LocalDelivery: 0
  Email::MIME::CreateHTML: 0
  HTML::Encoding: 0
  HTML::Entities: 0
  HTML::FormatText::WithLinks: 0
  HTML::TreeBuilder: 0
  MIME::EncWords: 0
  XML::Feed: 0
resources:
  license: http://dev.perl.org/licenses/
version: 1.1
